\."#################################################################
\."$Id: libnodeupdown.3,v 1.3 2003-03-11 22:28:15 achu Exp $
\."by Albert Chu <chu11@llnl.gov>
\."#################################################################
.\"
.TH LIBNODEUPDOWN 3 "Release 1.1" "LLNL" "LIBNODEUPDOWN"
.SH NAME
libnodeupdown \- a library of functions to determine if a node is up or down
.SH SYNOPSIS
.B #include <nodeupdown.h>
.sp
.BI "nodeupdown_t nodeupdown_create(void);"
.sp
.BI "int nodeupdown_load_data(nodeupdown_t handle, char *genders_filename, char *gmond_hostname, char *gmond_ip, int gmond_port);"
.sp
.BI "int nodeupdown_destroy(nodeupdown_t handle);"
.sp
.BI "int nodeupdown_errnum(nodeupdown_t handle);"
.sp
.BI "char *nodeupdown_strerror(int errnum);"
.sp
.BI "char *nodeupdown_errormsg(int errnum);"
.sp
.BI "void nodeupdown_perror(nodeupdown_t handle, char *msg);"
.sp
.BI "int nodeupdown_dump(nodeupdown_t handle, FILE *stream);"
.sp
.BI "int nodeupdown_get_up_nodes_string(nodeupdown_t handle, char *buf, int buflen);"
.sp
.BI "int nodeupdown_get_down_nodes_string(nodeupdown_t handle, char *buf, int buflen);"
.sp
.BI "int nodeupdown_get_up_nodes_list(nodeupdown_t handle, char **list, int len);"
.sp
.BI "int nodeupdown_get_down_nodes_list(nodeupdown_t handle, char **list, int len);"
.sp
.BI "int nodeupdown_get_up_nodes_string_altnames(nodeupdown_t handle, char *buf, int buflen);"
.sp
.BI "int nodeupdown_get_down_nodes_string_altnames(nodeupdown_t handle, char *buf, int buflen);"
.sp
.BI "int nodeupdown_get_up_nodes_list_altnames(nodeupdown_t handle, char **list, int len);"
.sp
.BI "int nodeupdown_get_down_nodes_list_altnames(nodeupdown_t handle, char **list, int len);"
.sp
.BI "int nodeupdown_is_node_up(nodeupdown_t handle, char *node);"
.sp
.BI "int nodeupdown_is_node_down(nodeupdown_t handle, char *node);"
.sp
.BI "int nodeupdown_convert_string_to_altnames(nodeupdown_t handle, char *src, char *dest, int buflen);"
.sp
.BI "int nodeupdown_convert_list_to_altnames(nodeupdown_t handle, char **src, char **dest, int len);"
.sp
.BI "int nodeupdown_nodelist_create(nodeupdown_t handle, char ***list);"
.sp
.BI "int nodeupdown_nodelist_clear(nodeupdown_t handle, char **list);"
.sp
.BI "int nodeupdown_nodelist_destroy(nodeupdown_t handle, char **list);"
.br
.SH DESCRIPTION
The nodeupdown library functions are a set of functions that interacts with
genders and ganglia to determine if a node is up or down.
For instructions on each of the functions, please see the comments written
in /usr/include/nodeupdown.h.
.br
.SH FILES
/usr/include/nodeupdown.h
.SH "SEE ALSO"
libgenders(3)
