\."#############################################################################
\."$Id: nodeupdown_load_data.3,v 1.21 2005-04-05 01:32:44 achu Exp $
\."#############################################################################
\."  Copyright (C) 2003 The Regents of the University of California.
\."  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
\."  Written by Albert Chu <chu11@llnl.gov>
\."  UCRL-CODE-155699
\."  
\."  This file is part of Whatsup, tools and libraries for determining up and
\."  down nodes in a cluster.  For details, see http://www.llnl.gov/linux/.
\."
\."  Whatsup is free software; you can redistribute it and/or modify it under
\."  the terms of the GNU General Public License as published by the Free
\."  Software Foundation; either version 2 of the License, or (at your option)
\."  any later version.
\."  
\."  Whatsup is distributed in the hope that it will be useful, but WITHOUT 
\."  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
\."  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
\."  for more details.
\."  
\."  You should have received a copy of the GNU General Public License along
\."  with Whatsup; if not, write to the Free Software Foundation, Inc.,
\."  59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
\."############################################################################
.TH NODEUPDOWN_LOAD_DATA 3 "November 2003" "LLNL" "LIBNODEUPDOWN"
.SH NAME
nodeupdown_load_data \- load data from ganglia
.SH SYNOPSIS
.B #include <nodeupdown.h>
.sp
.BI "int nodeupdown_load_data(nodeupdown_t handle, const char *hostname, int port, int timeout_len, char *reserved);"
.br
.SH DESCRIPTION
\fBnodeupdown_load_data()\fR loads data from the backend tool's
server so that the remaining nodeupdown library functions can properly
return information about up and down nodes.

\fIhandle\fR is a nodeupdown
handle created by
.BR nodeupdown_handle_create (3).  

\fIhostname\fR should indicate the location of the server.  If
\fIhostname\fR is NULL, nodeupdown assumes the server is on the local
node.

\fIport\fR should indicate the port number of the server.  If
\fIport\fR less than or equal to 0, nodeupdown assumes the server is
running on the backend tool's default port.

\fItimeout_len\fR should indicate the timeout length in seconds that
determines if a node is up or down.  If \fItimeout_len\fR is less than
or equal to 0, nodeupdown assumes the default timeout length defined
by NODEUPDOWN_TIMEOUT_LEN.
 
\fIreserved\fR is no longer used.  It remains for backwards
compatability with older libraries.

The default values used in \fBnodeupdown_load_data()\fR can
overwritten using the nodeupdown configuration file.  See
.BR nodeupdown.conf (5).
.br
.SH RETURN VALUES
On success, 0 is returned.  On error, -1 is returned, and an error
code is returned in \fIhandle\fR.  The error code can be retrieved via
.BR nodeupdown_errnum (3)
, and a description of the error code can be retrieved via
.BR nodeupdown_strerror (3).  
Error codes are defined in nodeupdown.h.
.br
.SH ERRORS
.TP
.B NODEUPDOWN_ERR_NULLHANDLE
The handle parameter is NULL.  The nodeupdown handle must be created
with
.BR nodeupdown_handle_create (3).
.TP
.B NODEUPDOWN_ERR_OPEN
A clusterlist database could not be opened.
.TP
.B NODEUPDOWN_ERR_CONNECT	
Error connecting to server specified by \fIhostname\fR and \fIgmond_port\fR.
.TP
.B NODEUPDOWN_ERR_TIMEOUT
Connection to server timed out.
.TP
.B NODEUPDOWN_ERR_HOSTNAME
Incorrect hostname specified by \fIhostname\fR.
.TP
.B NODEUPDOWN_ERR_ADDRESS
Incorrect network address specified by \fIhostname\fR.
.TP
.B NODEUPDOWN_ERR_NETWORK
Internal network failure.
.TP
.B NODEUPDOWN_ERR_ISLOADED
.BR nodeupdown_load_data (3) 
has already been called with \fIhandle\fR.  
.TP
.B NODEUPDOWN_ERR_PARAMETERS
An incorrect parameter has been passed in.
.TP
.B NODEUPDOWN_ERR_OUTMEM
.BR malloc (3)
has failed internally.
.TP
.B NODEUPDOWN_ERR_CLUSTERLIST
Internal error with the cluster list of nodes.
.TP
.B NODEUPDOWN_ERR_CLUSTERLIST_OPEN
Error opening the cluster list of nodes database.
.TP
.B NODEUPDOWN_ERR_CLUSTERLIST_READ
Error reading the cluster list of nodes database.
.TP
.B NODEUPDOWN_ERR_CLUSTERLIST_PARSE
Error parsing the cluster list of nodes database.
.TP
.B NODEUPDOWN_ERR_XML
XML parsing error
.TP
.B NODEUPDOWN_ERR_CONF
Nodeupdown configuration file error
.TP
.B NODEUPDOWN_ERR_HOSTLIST
Hostlist API has failed internally.
.TP
.B NODEUPDOWN_ERR_MAGIC 
\fIhandle\fR has an incorrect magic number.  \fIhandle\fR does not
point to a nodeupdown handle or \fIhandle\fR has been destroyed by
.BR nodeupdown_handle_destroy (3).
.TP
.B NODEUPDOWN_ERR_INTERNAL
An internal system error has occurred.  
.br
.SH FILES
/usr/include/nodeupdown.h
.SH SEE ALSO
libnodeupdown(3), nodeupdown_handle_create(3),
nodeupdown_handle_destroy(3), nodeupdown_errnum(3),
nodeupdown_strerror(3), nodeupdown.conf(5)
