.\"#############################################################################
.\"$Id: nodeupdown_errnum.3,v 1.9 2010-02-02 00:01:53 chu11 Exp $
.\"#############################################################################
.\"  Copyright (C) 2007-2015 Lawrence Livermore National Security, LLC.
.\"  Copyright (C) 2003-2007 The Regents of the University of California.
.\"  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
.\"  Written by Albert Chu <chu11@llnl.gov>
.\"  UCRL-CODE-155699
.\"
.\"  This file is part of Whatsup, tools and libraries for determining up and
.\"  down nodes in a cluster.  For details, see http://www.llnl.gov/linux/.
.\"
.\"  Whatsup is free software; you can redistribute it and/or modify it under
.\"  the terms of the GNU General Public License as published by the Free
.\"  Software Foundation; either version 2 of the License, or (at your option)
.\"  any later version.
.\"
.\"  Whatsup is distributed in the hope that it will be useful, but WITHOUT
.\"  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
.\"  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\"  for more details.
.\"
.\"  You should have received a copy of the GNU General Public License along
.\"  with Whatsup.  If not, see <http://www.gnu.org/licenses/>.
.\"############################################################################
.TH NODEUPDOWN_ERRNUM 3 "August 2003" "LLNL" "LIBNODEUPDOWN"
.SH NAME
nodeupdown_errnum, nodeupdown_strerror, nodeupdown_errormsg,
nodeupdown_perror \- nodeupdown error routines
.SH SYNOPSIS
.B #include <nodeupdown.h>
.sp
.BI "int nodeupdown_errnum(nodeupdown_t handle);"
.sp
.BI "char *nodeupdown_strerror(int errnum);"
.sp
.BI "char *nodeupdown_errormsg(nodeupdown_t handle);"
.sp
.BI "void nodeupdown_perror(nodeupdown_t handle, const char *msg);"
.br
.SH DESCRIPTION
\fBnodeupdown_errnum()\fR returns the error code stored in
\fIhandle\fR.

\fBnodeupdown_strerror()\fR returns a pointer to a string describing the error code
\fIerrnum\fR.

Generally, an error code is retrieved by \fBnodeupdown_errnum()\fR and
then passed to \fBnodeupdown_strerror()\fR.

\fBnodeupdown_errormsg()\fR returns a pointer to a string describing
the error stored in \fIhandle\fR.  It is logically equivalent to:

char *nodeupdown_strerror(nodeupdown_errnum(nodeupdown_t handle));

\fBnodeupdown_perror()\fR is similar to
.BR perror (3).
It produces a message on standard error output, describing the error
stored in \fIhandle\fR.  If \fImsg\fR is not NULL, the string pointed
to by \fImsg\fR, a colon, and a blank are printed before the error
message.

.br
.SH FILES
/usr/include/nodeupdown.h
