.\"#############################################################################
.\"$Id: nodeupdown_up_count.3,v 1.8 2010-02-02 00:01:53 chu11 Exp $
.\"#############################################################################
.\"  Copyright (C) 2007-2015 Lawrence Livermore National Security, LLC.
.\"  Copyright (C) 2003-2007 The Regents of the University of California.
.\"  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
.\"  Written by Albert Chu <chu11@llnl.gov>
.\"  UCRL-CODE-155699
.\"  
.\"  This file is part of Whatsup, tools and libraries for determining up and
.\"  down nodes in a cluster.  For details, see http://www.llnl.gov/linux/.
.\"
.\"  Whatsup is free software; you can redistribute it and/or modify it under
.\"  the terms of the GNU General Public License as published by the Free
.\"  Software Foundation; either version 2 of the License, or (at your option)
.\"  any later version.
.\"  
.\"  Whatsup is distributed in the hope that it will be useful, but WITHOUT 
.\"  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
.\"  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
.\"  for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License along
.\"  with Whatsup.  If not, see <http://www.gnu.org/licenses/>.
.\"############################################################################
.TH NODEUPDOWN_UP_COUNT 3 "September 2003" "LLNL" "LIBNODEUPDOWN"
.SH NAME
nodeupdown_up_count, nodeupdown_down_count \- return the number of nodes that are up or down
.SH SYNOPSIS
.B #include <nodeupdown.h>
.sp
.BI "int nodeupdown_up_count(nodeupdown_t handle);"
.sp
.BI "int nodeupdown_down_count(nodeupdown_t handle);"
.br
.SH DESCRIPTION
\fBnodeupdown_up_count()\fR returns the number of nodes that are up.

\fBnodeupdown_down_count()\fR returns the number of nodes that are down.

.br
.SH RETURN VALUES
On success, \fBnodeupdown_up_count()\fR and
\fBnodeupdown_down_count()\fR will return the number of up or down
nodes respectively. On error, both return -1, and an error code is
returned in \fIhandle\fR.  The error code can be retrieved via
.BR nodeupdown_errnum (3), 
and a description of the error code can be retrieved via 
.BR nodeupdown_strerror (3).  
Error codes are defined in nodeupdown.h.
.br
.SH ERRORS
.TP
.B NODEUPDOWN_ERR_NULLHANDLE
The handle parameter is NULL.  The nodeupdown handle must be created
with
.BR nodeupdown_handle_create (3).
.TP
.B NODEUPDOWN_ERR_NOTLOADED
.BR nodeupdown_load_data (3)
has not been called and no data has been retrieved.
.TP
.B NODEUPDOWN_ERR_MAGIC 
\fIhandle\fR has an incorrect magic number.  \fIhandle\fR does not
point to a nodeupdown handle or \fIhandle\fR has been destroyed by
.BR nodeupdown_handle_destroy (3).
.br
.SH FILES
/usr/include/nodeupdown.h
.SH SEE ALSO
libnodeupdown(3), nodeupdown_handle_create(3),
nodeupdown_load_data(3), nodeupdown_errnum(3), nodeupdown_strerror(3)
