all:
	cp ../src/libnodeupdown/nodeupdown.c .
	cp ../src/libnodeupdown/hostlist.c .
	cp ../src/libnodeupdown/nodeupdown.h .
	cp ../src/libnodeupdown/hostlist.h .
	gcc -g -Wall -o libnodeupdown_test libnodeupdown_test.c nodeupdown.c hostlist.c -lgendersllnl -lganglia


