all:
	# to compile and debug nodeupdown.c
	gcc -g -Wall -o libnodeupdown_test libnodeupdown_test.c nodeupdown.c hostlist.c -lgenders -lganglia
	# to test the real way
	# gcc -g -Wall -o libnodeupdown_test libnodeupdown_test.c -lnodeupdown

